openapi: 3.0.0
info:
  version: 1.0.0
  title: Photo-Blog
  description: Photo-Blog API 문서입니다
  license:
    name: MIT
servers:
  - description: dev server
    url: 'http://localhost:8000'
paths:
  /user/test:
    get:
      parameters:
        - in: query
          name: end
          schema:
            type: integer
          description: 2~9999까지 숫자를 넣으면 1~end까지 테스트 유저가 생성 (default = 2)
      tags:
        - /user
      summary: 테스트 유저 생성
      responses:
        '201':
          description: 유저 생성 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: 응답 상태 코드
                    example: 201
                  data:
                    type: object
                    properties:
                      message:
                        type: string;
                        example: 테스트 계정을 생성 완료 했습니다.
  /user/admin:
    get:
      tags:
        - /user
      summary: 관리자 계정 생성
      responses:
        '201':
          description: 관리자 계정 생성 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: 응답 상태 코드
                    example: 201
                  data:
                    type: object
                    properties:
                      userId:
                        type: string;
                        example: userId
  /user:
    post:
      tags:
        - /user
      summary: 회원가입
  /user/find:
    get:
      tags:
        - /user
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          description: 사용 할 유저 아이디 입력
      summary: 아이디 중복 체크
      responses:
        '200':
          description: 관리자 계정 생성 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: 응답 상태 코드
                    example: 200
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: 이용 가능한 아이디 입니다
  /user/login:
    post:
      tags:
        - /user
      summery: 로그인
  /user/manage:
    get:
      tags:
        - /user
      summery: 유저 리스트
components:
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
            properties: null
